// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StructField } from '../golang/struct-field.js';


export class GoType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GoType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGoType(bb:flatbuffers.ByteBuffer, obj?:GoType):GoType {
  return (obj || new GoType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGoType(bb:flatbuffers.ByteBuffer, obj?:GoType):GoType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GoType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

elem():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

methods(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

methodsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

fields(index: number, obj?:StructField):StructField|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new StructField()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fieldsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

params(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

paramsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

results(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

resultsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

method():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

key():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

dir():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

size():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startGoType(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addElem(builder:flatbuffers.Builder, elem:number) {
  builder.addFieldInt32(0, elem, 0);
}

static addMethods(builder:flatbuffers.Builder, methodsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, methodsOffset, 0);
}

static createMethodsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startMethodsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static addFields(builder:flatbuffers.Builder, fieldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, fieldsOffset, 0);
}

static createFieldsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFieldsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addParams(builder:flatbuffers.Builder, paramsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, paramsOffset, 0);
}

static createParamsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startParamsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static addResults(builder:flatbuffers.Builder, resultsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, resultsOffset, 0);
}

static createResultsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startResultsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static addMethod(builder:flatbuffers.Builder, method:bigint) {
  builder.addFieldInt64(5, method, BigInt('0'));
}

static addKey(builder:flatbuffers.Builder, key:number) {
  builder.addFieldInt32(6, key, 0);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldInt32(7, value, 0);
}

static addDir(builder:flatbuffers.Builder, dir:number) {
  builder.addFieldInt32(8, dir, 0);
}

static addSize(builder:flatbuffers.Builder, size:bigint) {
  builder.addFieldInt64(9, size, BigInt('0'));
}

static endGoType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGoType(builder:flatbuffers.Builder, elem:number, methodsOffset:flatbuffers.Offset, fieldsOffset:flatbuffers.Offset, paramsOffset:flatbuffers.Offset, resultsOffset:flatbuffers.Offset, method:bigint, key:number, value:number, dir:number, size:bigint):flatbuffers.Offset {
  GoType.startGoType(builder);
  GoType.addElem(builder, elem);
  GoType.addMethods(builder, methodsOffset);
  GoType.addFields(builder, fieldsOffset);
  GoType.addParams(builder, paramsOffset);
  GoType.addResults(builder, resultsOffset);
  GoType.addMethod(builder, method);
  GoType.addKey(builder, key);
  GoType.addValue(builder, value);
  GoType.addDir(builder, dir);
  GoType.addSize(builder, size);
  return GoType.endGoType(builder);
}
}
