// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Kind {
  nil = 0,
  int = 1,
  int8 = 2,
  int16 = 3,
  int32 = 4,
  int64 = 5,
  uint8 = 6,
  uint16 = 7,
  uint32 = 8,
  uint64 = 9,
  uintptr = 10,
  float32 = 11,
  float64 = 12,
  complex64 = 13,
  complex128 = 14,
  string = 15,
  rune = 16,
  byte = 17,
  boolean = 18,
  pointer = 19,
  struct = 20,
  func = 21,
  array = 22,
  slice = 23,
  map = 24,
  channel = 25,
  interface_ = 26
}
