// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Kind {
  Nil = 0,
  Int = 1,
  Int8 = 2,
  Int16 = 3,
  Int32 = 4,
  Int64 = 5,
  Uint8 = 6,
  Uint16 = 7,
  Uint32 = 8,
  Uint64 = 9,
  Uintptr = 10,
  Float32 = 11,
  Float64 = 12,
  Complex64 = 13,
  Complex128 = 14,
  String = 15,
  Rune = 16,
  Byte = 17,
  Boolean = 18,
  Pointer = 19,
  Struct = 20,
  Func = 21,
  Array = 22,
  Slice = 23,
  Map = 24,
  Channel = 25,
  Interface = 26
}
