// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum NodeFlag {
  None = 1,
  NodeIndexed = 2,
  NodeBinary = 4,
  NodeUnary = 8
}
