// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StructField {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StructField {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

name():number {
  return this.bb!.readUint32(this.bb_pos);
}

type():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

misc():number {
  return this.bb!.readUint32(this.bb_pos + 8);
}

static sizeOf():number {
  return 12;
}

static createStructField(builder:flatbuffers.Builder, name: number, type: number, misc: number):flatbuffers.Offset {
  builder.prep(4, 12);
  builder.writeInt32(misc);
  builder.writeInt32(type);
  builder.writeInt32(name);
  return builder.offset();
}

}
