// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ValueFlag {
  None = 1,
  Pointer = 2,
  Quotation = 4,
  IfConditon = 8,
  IfBody = 16,
  IfElse = 32,
  FuncMeta = 64,
  FuncParam = 128,
  FuncBody = 256,
  SwitchExp = 512,
  SwitchBody = 1024,
  CaseExp = 2048,
  CaseBody = 4096,
  ForInit = 8192,
  ForCondition = 16384,
  ForPost = 32768,
  ForBody = 65536,
  ForRangeVar1 = 131072,
  ForRangeVar2 = 262144,
  ForRangeValue = 524288,
  DefaultBody = 1048576
}
