// automatically generated by the FlatBuffers compiler, do not modify

import { BinaryNode } from '../program/binary-node';
import { IndexedNode } from '../program/indexed-node';
import { UnaryNode } from '../program/unary-node';


export enum NodeUnion{
  NONE = 0,
  IndexedNode = 1,
  BinaryNode = 2,
  UnaryNode = 3
}

export function unionToNodeUnion(
  type: NodeUnion,
  accessor: (obj:BinaryNode|IndexedNode|UnaryNode) => BinaryNode|IndexedNode|UnaryNode|null
): BinaryNode|IndexedNode|UnaryNode|null {
  switch(NodeUnion[type]) {
    case 'NONE': return null; 
    case 'IndexedNode': return accessor(new IndexedNode())! as IndexedNode;
    case 'BinaryNode': return accessor(new BinaryNode())! as BinaryNode;
    case 'UnaryNode': return accessor(new UnaryNode())! as UnaryNode;
    default: return null;
  }
}

export function unionListToNodeUnion(
  type: NodeUnion, 
  accessor: (index: number, obj:BinaryNode|IndexedNode|UnaryNode) => BinaryNode|IndexedNode|UnaryNode|null, 
  index: number
): BinaryNode|IndexedNode|UnaryNode|null {
  switch(NodeUnion[type]) {
    case 'NONE': return null; 
    case 'IndexedNode': return accessor(index, new IndexedNode())! as IndexedNode;
    case 'BinaryNode': return accessor(index, new BinaryNode())! as BinaryNode;
    case 'UnaryNode': return accessor(index, new UnaryNode())! as UnaryNode;
    default: return null;
  }
}

