// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class NodeValue {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NodeValue {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

value():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

type():number {
  return this.bb!.readUint32(this.bb_pos + 8);
}

flags():number {
  return this.bb!.readUint32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createNodeValue(builder:flatbuffers.Builder, value: bigint, type: number, flags: number):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt32(flags);
  builder.writeInt32(type);
  builder.writeInt64(BigInt(value ?? 0));
  return builder.offset();
}

}
