// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StructureField {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StructureField {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStructureField(bb:flatbuffers.ByteBuffer, obj?:StructureField):StructureField {
  return (obj || new StructureField()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStructureField(bb:flatbuffers.ByteBuffer, obj?:StructureField):StructureField {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StructureField()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

type():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

misc():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startStructureField(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addName(builder:flatbuffers.Builder, name:number) {
  builder.addFieldInt32(0, name, 0);
}

static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt32(1, type, 0);
}

static addMisc(builder:flatbuffers.Builder, misc:number) {
  builder.addFieldInt32(2, misc, 0);
}

static endStructureField(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStructureField(builder:flatbuffers.Builder, name:number, type:number, misc:number):flatbuffers.Offset {
  StructureField.startStructureField(builder);
  StructureField.addName(builder, name);
  StructureField.addType(builder, type);
  StructureField.addMisc(builder, misc);
  return StructureField.endStructureField(builder);
}
}
