// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class TupleType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):TupleType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTupleType(bb:flatbuffers.ByteBuffer, obj?:TupleType):TupleType {
  return (obj || new TupleType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTupleType(bb:flatbuffers.ByteBuffer, obj?:TupleType):TupleType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TupleType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

elem(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

elemLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

elemArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startTupleType(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addElem(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, elemOffset, 0);
}

static createElemVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createElemVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createElemVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startElemVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endTupleType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTupleType(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset):flatbuffers.Offset {
  TupleType.startTupleType(builder);
  TupleType.addElem(builder, elemOffset);
  return TupleType.endTupleType(builder);
}
}
