// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Type, unionToType, unionListToType } from '../program/type.js';


export class TypeDef {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TypeDef {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTypeDef(bb:flatbuffers.ByteBuffer, obj?:TypeDef):TypeDef {
  return (obj || new TypeDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTypeDef(bb:flatbuffers.ByteBuffer, obj?:TypeDef):TypeDef {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TypeDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

base():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

typeType():Type {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Type.NONE;
}

type<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

flags():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startTypeDef(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addBase(builder:flatbuffers.Builder, base:number) {
  builder.addFieldInt32(0, base, 0);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(1, id, 0);
}

static addTypeType(builder:flatbuffers.Builder, typeType:Type) {
  builder.addFieldInt8(2, typeType, Type.NONE);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, typeOffset, 0);
}

static addFlags(builder:flatbuffers.Builder, flags:number) {
  builder.addFieldInt32(4, flags, 0);
}

static endTypeDef(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTypeDef(builder:flatbuffers.Builder, base:number, id:number, typeType:Type, typeOffset:flatbuffers.Offset, flags:number):flatbuffers.Offset {
  TypeDef.startTypeDef(builder);
  TypeDef.addBase(builder, base);
  TypeDef.addId(builder, id);
  TypeDef.addTypeType(builder, typeType);
  TypeDef.addType(builder, typeOffset);
  TypeDef.addFlags(builder, flags);
  return TypeDef.endTypeDef(builder);
}
}
