// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ArrayType } from '../program/array-type.js';
import { FunctionType } from '../program/function-type.js';
import { MapType } from '../program/map-type.js';
import { PointerType } from '../program/pointer-type.js';
import { StructureType } from '../program/structure-type.js';
import { TupleType } from '../program/tuple-type.js';


export enum Type {
  NONE = 0,
  PointerType = 1,
  StructureType = 2,
  FunctionType = 3,
  MapType = 4,
  ArrayType = 5,
  TupleType = 6
}

export function unionToType(
  type: Type,
  accessor: (obj:ArrayType|FunctionType|MapType|PointerType|StructureType|TupleType) => ArrayType|FunctionType|MapType|PointerType|StructureType|TupleType|null
): ArrayType|FunctionType|MapType|PointerType|StructureType|TupleType|null {
  switch(Type[type]) {
    case 'NONE': return null; 
    case 'PointerType': return accessor(new PointerType())! as PointerType;
    case 'StructureType': return accessor(new StructureType())! as StructureType;
    case 'FunctionType': return accessor(new FunctionType())! as FunctionType;
    case 'MapType': return accessor(new MapType())! as MapType;
    case 'ArrayType': return accessor(new ArrayType())! as ArrayType;
    case 'TupleType': return accessor(new TupleType())! as TupleType;
    default: return null;
  }
}

export function unionListToType(
  type: Type, 
  accessor: (index: number, obj:ArrayType|FunctionType|MapType|PointerType|StructureType|TupleType) => ArrayType|FunctionType|MapType|PointerType|StructureType|TupleType|null, 
  index: number
): ArrayType|FunctionType|MapType|PointerType|StructureType|TupleType|null {
  switch(Type[type]) {
    case 'NONE': return null; 
    case 'PointerType': return accessor(index, new PointerType())! as PointerType;
    case 'StructureType': return accessor(index, new StructureType())! as StructureType;
    case 'FunctionType': return accessor(index, new FunctionType())! as FunctionType;
    case 'MapType': return accessor(index, new MapType())! as MapType;
    case 'ArrayType': return accessor(index, new ArrayType())! as ArrayType;
    case 'TupleType': return accessor(index, new TupleType())! as TupleType;
    default: return null;
  }
}
