// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { GoType } from '../go/golang/go-type.js';


export enum Type {
  NONE = 0,
  golang_GoType = 1
}

export function unionToType(
  type: Type,
  accessor: (obj:GoType) => GoType|null
): GoType|null {
  switch(Type[type]) {
    case 'NONE': return null; 
    case 'golang_GoType': return accessor(new GoType())! as GoType;
    default: return null;
  }
}

export function unionListToType(
  type: Type, 
  accessor: (index: number, obj:GoType) => GoType|null, 
  index: number
): GoType|null {
  switch(Type[type]) {
    case 'NONE': return null; 
    case 'golang_GoType': return accessor(index, new GoType())! as GoType;
    default: return null;
  }
}
