import * as fb from "flatbuffers";
import * as go from "./golang";
import * as program from "../program";
import {
  GoArrayType,
  GoFunctionType,
  GoInterfaceType,
  GoKind,
  GoMapType,
  GoPointerType,
  GoStruct,
  GoStructType,
  GoType,
  GoTypeDef,
  KindMapper,
} from "./types";
import {
  NodeId,
  INode,
  INodeValue,
  IBuilder,
  BuilderOptions,
} from "../ibuilder";
import { packIntArrayToBigInt } from "./utils";

export interface GoBuilderOptions extends BuilderOptions {}

export interface GoNodeValue extends INodeValue {
  type?: GoTypeDef;
}

export interface Node extends INode<go.Opcode, GoNodeValue> {}

export interface FuncImpl {
  type: GoTypeDef; // Must be of GoFuncType
  params?: NodeId[]; // Input parameters
  body?: NodeId[]; // Array of node id
}

/**
 * Go-specific implementation of the generic builder.
 *
 * The Go source code is generated by a separate compiler
 * that consumes the FlatBuffers IR produced here.
 */
export class GoBuilder extends IBuilder<go.Opcode, go.NodeFlag, go.ValueFlag> {
  constructor(private options: GoBuilderOptions) {
    super(options);
  }

  protected buildNode(node: Node, id: NodeId): fb.Offset {
    let nodeType = program.NodeUnion.NONE;
    let nodeContentOffset: fb.Offset = 0;
    switch (node.flags) {
      case go.NodeFlag.NodeIndexed:
        nodeType = program.NodeUnion.IndexedNode;
        nodeContentOffset = this.CreateIndexedNode(node);
        break;
      case go.NodeFlag.NodeBinary:
        nodeType = program.NodeUnion.BinaryNode;
        nodeContentOffset = this.CreateBinaryNode(node);
        break;
      case go.NodeFlag.NodeUnary:
        nodeType = program.NodeUnion.UnaryNode;
        nodeContentOffset = this.CreateUnaryNode(node);
        break;
    }

    program.Node.startNode(this.builder);
    program.Node.addOpcode(this.builder, node.opcode);

    // console.log(`id: ${id}`);
    program.Node.addId(this.builder, id);
    program.Node.addParent(this.builder, node.parent || 0n);
    program.Node.addNext(this.builder, node.next || 0n);
    program.Node.addFlags(this.builder, node.flags);
    program.Node.addNodeType(this.builder, nodeType);
    program.Node.addNode(this.builder, nodeContentOffset);
    return program.Node.endNode(this.builder);
  }

  public SetNode(node: Node, id?: NodeId): NodeId {
    let _id = id || BigInt(this.nodes.size);
    if (this.nodes.has(_id)) return this.SetNode(node, ++_id); // Retry with new id if exists

    const nodeOffset = this.buildNode(node, _id);
    this.nodes.set(_id, [node, nodeOffset]);
    return _id;
  }

  public DeleteNode(id: NodeId, recursive: boolean = false) {
    if (!this.nodes.has(id)) {
      console.error(`Unknown id of ${id}`);
      return;
    }

    if (!recursive) {
      this.detachNode(id);
      this.nodes.delete(id);
      return;
    }

    this.deleteRecursive(id);
  };

  private deleteRecursive(id: NodeId, visited: Set<NodeId> = new Set<NodeId>()) {
    if (visited.has(id)) return;
    visited.add(id);

    const entry = this.nodes.get(id);
    if (!entry) return;

    const [ node, offset ] = entry;

    // Traverse children based on node type
    switch (node.flags) {
      case go.NodeFlag.NodeIndexed:
        for (const n of node.fields || []) {
          if ((n.flags & go.ValueFlag.Pointer) === 0)
            continue;
          
          this.deleteRecursive(n.value as NodeId, visited);
        }
        break;

      case go.NodeFlag.NodeBinary:
        if (node.left && (node.left.flags & go.ValueFlag.Pointer)) {
          this.deleteRecursive(node.left.value as NodeId, visited);
        }

        if (node.right && (node.right.flags & go.ValueFlag.Pointer)) {
          this.deleteRecursive(node.right.value as NodeId, visited);
        }
        break;

      case go.NodeFlag.NodeUnary:
        if (node.value && (node.value.flags & go.ValueFlag.Pointer)) {
          this.deleteRecursive(node.value.value as NodeId, visited);
        }
        break;
    }

    this.detachNode(id);
    this.nodes.delete(id);
  }

  private detachNode(id: NodeId) {
    const entry = this.nodes.get(id);
    if (!entry) return;

    const node = entry[0];

    // Remove from parent.next
    if (node.parent !== void 0 && this.nodes.has(node.parent)) {
      const parentEntry = this.nodes.get(node.parent)!;

      if (parentEntry[0].next === id) {
        parentEntry[0].next = undefined;
      }
    }

    // Remove next.parent
    if (node.next && this.nodes.has(node.next)) {
      const nextEntry = this.nodes.get(node.next)!;

      if (nextEntry[0].parent === id) {
        nextEntry[0].parent = undefined;
      }
    }
  }

  /**
   * Updates a single indexed field on an existing node.
   *
   * This is used for inline edits such as:
   * renaming identifiers, changing literal values, modifying parameters.
   *
   * The node is immediately re-serialized.
   */
  public UpdateNodeField(id: NodeId, index: number, field: GoNodeValue) {
    const node = this.nodes.get(id);
    if (!node || !node[0].fields) {
      console.error(`Invalid node ${id}.`);
      return;
    }

    if (index < 0 || index > node[0].fields.length) {
      console.error(`Invalid index of ${index}.`);
      return;
    }

    node[0].fields[index] = field;
    const nodeOffset = this.buildNode(node[0], id);
    this.nodes.set(id, [node[0], nodeOffset]);
  }

  /**
   * Connects two nodes structurally.
   *
   * This defines ordering and containment in the graph:
   *  - parent.next = child
   *  - child.parent = parent
   *
   * Frontend equivalent: dragging one block under another.
   *
   * @param parent The container or previous node
   * @param child The node being attached
   */
  public ConnectNodes(parent: NodeId, child: NodeId) {
    const targetNode = this.nodes.get(parent);
    if (!targetNode) {
      console.error(`Could not find node with ${parent}.`);
      return;
    }

    const sourceNode = this.nodes.get(child);
    if (!sourceNode) {
      console.error(`Could not find node with ${child}.`);
      return;
    }

    targetNode[0].next = child;
    sourceNode[0].parent = parent;

    targetNode[0].parent = -1n;
    sourceNode[0].next = -1n;
    const targetNodeOffset = this.buildNode(targetNode[0], parent);
    const sourceNodeOffset = this.buildNode(sourceNode[0], child);
    this.nodes.set(parent, [targetNode[0], targetNodeOffset]);
    this.nodes.set(child, [sourceNode[0], sourceNodeOffset]);
  }

  public CreateNode(opcode: go.Opcode, flags: number): Node {
    return {
      opcode,
      flags,
    };
  }

  private makeValue(v: string | NodeId, t?: GoTypeDef): GoNodeValue {
    let flags: number;

    if (typeof v === "bigint") {
      flags = go.ValueFlag.Pointer;
    } else {
      flags = this.isValidNumber(v)
        ? go.ValueFlag.None
        : go.ValueFlag.Quotation;
    }

    return { type: t, value: v, flags };
  }

  private makePtr(v: NodeId): GoNodeValue {
    return {
      value: v,
      flags: go.ValueFlag.Pointer,
    };
  }

  private makePtrFields(values: NodeId[]): GoNodeValue[] {
    return values.map((v) => this.makePtr(v));
  }

  private createUnary(opcode: go.Opcode, a: string | NodeId): Node {
    return {
      opcode,
      flags: go.NodeFlag.NodeUnary,
      value: this.makeValue(a),
    };
  }

  private createBinary(
    opcode: go.Opcode,
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return {
      opcode,
      flags: go.NodeFlag.NodeBinary,
      left: this.makeValue(a),
      right: this.makeValue(b),
    };
  }

  private createIndexed(
    opcode: go.Opcode,
    id?: string,
    fields?: GoNodeValue[],
  ): Node {
    let idOffset: fb.Offset | undefined;
    if (id !== void 0) idOffset = this.SetString(id);

    return {
      opcode,
      flags: go.NodeFlag.NodeIndexed,
      id: idOffset,
      fields,
    };
  }

  private isValidNumber(str: string): boolean {
    return !isNaN(Number(str));
  }

  /**
   * Creates a Go package declaration.
   *
   * @example
   * ```ts
   * const pkgId = builder.SetNode(
   *   builder.CreatePackageNode("main")
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * package main
   * ```
   */
  public CreatePackageNode(id: string): Node {
    if (id.trim().length <= 0)
      throw new Error("Package name must be non-empty");

    // TODO: Add regex check to evaluate if id is valid

    return this.createIndexed(go.Opcode.Package, id);
  }

  /**
   * Creates an import block.
   *
   * @example
   * ```ts
   * const fmtId = builder.SetNode(
   *   builder.CreateImportValueNode("fmt")
   * );
   *
   * const httpId = builder.SetNode(
   *   builder.CreateImportValueNode("net/http", "http")
   * );
   *
   * const importId = builder.SetNode(
   *   builder.CreateImportNode(fmtId, httpId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * import (
   *   "fmt"
   *   http "net/http"
   * )
   * ```
   */
  public CreateImportNode(...imports: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Import,
      undefined,
      this.makePtrFields(imports),
    );
  }

  public CreateImportValueNode(path: string, alias?: string): Node {
    return this.createBinary(go.Opcode.ImportValue, alias ?? "", path);
  }

  /**
   * Creates a constant declaration.
   *
   * @example
   * ```ts
   * const piId = builder.SetNode(
   *   builder.CreateConstValueNode("pi", floatType, "3.14")
   * );
   *
   * const constId = builder.SetNode(
   *   builder.CreateConstNode(piId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * const pi = 3.14
   * ```
   */
  public CreateConstNode(...constants: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Const,
      undefined,
      this.makePtrFields(constants),
    );
  }

  public CreateConstValueNode(
    name: string,
    type: GoTypeDef,
    value: string,
  ): Node {
    return {
      opcode: go.Opcode.ConstValue,
      flags: go.NodeFlag.NodeBinary,

      left: this.makeValue(name, type),
      right: this.makeValue(value),
    };
  }

  /**
   * Creates a variable declaration.
   *
   * @example
   * ```ts
   * const xId = builder.SetNode(
   *   builder.CreateVarValueNode("x", intType, "0")
   * );
   *
   * const varId = builder.SetNode(
   *   builder.CreateVarNode(xId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * var x = 0
   * ```
   */
  public CreateVarNode(...vars: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Var,
      undefined,
      this.makePtrFields(vars),
    );
  }

  public CreateVarValueNode(
    name: string,
    type: GoTypeDef,
    value: string,
  ): Node {
    return {
      opcode: go.Opcode.VarValue,
      flags: go.NodeFlag.NodeBinary,

      left: this.makeValue(name, type),
      right: this.makeValue(value),
    };
  }

  /**
   * Creates a type declaration.
   *
   * @example
   * ```ts
   * const typeId = builder.SetNode(
   *   builder.CreateTypeNode(myStructType)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * type MyStruct struct { ... }
   * ```
   */
  public CreateTypeNode(type: GoTypeDef): Node {
    return this.createIndexed(go.Opcode.Type, type.id, [
      {
        type,
        value: 0n,
        flags: go.ValueFlag.None,
      },
    ]);
  }

  /**
   * Creates a `func` node.
   *
   * The function signature is defined by `type`.
   * Parameters and body are referenced via {@link NodeId}s and
   * stored as indexed fields with semantic flags.
   *
   * Compiler output:
   * ```go
   * func main() {}
   * ```
   */
  public CreateFuncNode(def: FuncImpl): Node {
    const meta: GoNodeValue = {
      type: def.type,
      value: 0n,
      flags: go.ValueFlag.FuncMeta,
    };

    const params =
      def.params?.map((v) => ({
        value: v,
        flags: go.ValueFlag.Pointer | go.ValueFlag.FuncParam,
      })) ?? [];

    const body =
      def.body?.map((v) => ({
        value: v,
        flags: go.ValueFlag.Pointer | go.ValueFlag.FuncBody, // WARN - Add proper value flag definition
      })) ?? [];

    return this.createIndexed(go.Opcode.Func, def.type.id, [
      meta,
      ...params,
      ...body,
    ]);
  }

  /**
   * Creates an if / else statement.
   *
   * @example
   * ```ts
   * const condId = builder.SetNode(
   *   builder.CreateGreaterNode(xId, yId)
   * );
   *
   * const ifId = builder.SetNode(
   *   builder.CreateIfNode(condId, [ thenStmtId ], [ elseStmtId ])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * if x > y {
   *   ...
   * } else {
   *   ...
   * }
   * ```
   */
  public CreateIfNode(
    condition: NodeId,
    body: NodeId[],
    _else: NodeId[] = [],
  ): Node {
    return this.createIndexed(go.Opcode.If, undefined, [
      {
        value: condition,
        flags: go.ValueFlag.Pointer | go.ValueFlag.IfConditon, // WARN - Add proper value flag definition
      },
      ...body.map((v) => {
        return {
          value: v,
          flags: go.ValueFlag.Pointer | go.ValueFlag.IfBody, // WARN - Add proper value flag definition
        };
      }),
      ..._else.map((v) => {
        return {
          value: v,
          flags: go.ValueFlag.Pointer | go.ValueFlag.IfElse, // WARN - Add proper value flag definition
        };
      }),
    ]);
  }

  /**
   * Creates a classic for-loop.
   *
   * @example
   * ```ts
   * const forId = builder.SetNode(
   *   builder.CreateForNode(initId, condId, postId, bodyIds)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * for init; cond; post {
   *   ...
   * }
   * ```
   */
  public CreateForNode(
    init: NodeId,
    cond: NodeId,
    post: NodeId,
    body: NodeId[],
  ): Node {
    return this.createIndexed(go.Opcode.For, undefined, [
      this.makePtr(init),
      this.makePtr(cond),
      this.makePtr(post),
      ...this.makePtrFields(body),
    ]);
  }

  /**
   * Creates a range-based for loop.
   *
   * @example
   * ```ts
   * const rangeId = builder.SetNode(
   *   builder.CreateForRangeNode(keyId, valueId, sliceId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * for k, v := range slice {
   *   ...
   * }
   * ```
   */
  public CreateForRangeNode(
    var1: NodeId, // First variable assignment
    var2: NodeId, // Second varable assignment
    value: NodeId, // Ranged value
  ): Node {
    return this.createIndexed(go.Opcode.ForRange, undefined, [
      this.makePtr(var1),
      this.makePtr(var2),
      this.makePtr(value),
    ]);
  }

  /**
   * Creates a switch statement.
   *
   * @example
   * ```ts
   * const switchId = builder.SetNode(
   *   builder.CreateSwitchNode(exprId, [ caseId, defaultId ])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * switch expr {
   * case x:
   *   ...
   * default:
   *   ...
   * }
   * ```
   */
  public CreateSwitchNode(expression: NodeId, body: NodeId[]): Node {
    return this.createIndexed(go.Opcode.Switch, undefined, [
      /*this.makePtr(expression),*/ ...this.makePtrFields(body),
    ]);
  }

  /**
   * Creates a select statement.
   *
   * @example
   * ```ts
   * const selectId = builder.SetNode(
   *   builder.CreateSelectNode([ caseId ])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * select {
   * case <-ch:
   *   ...
   * }
   * ```
   */
  public CreateSelectNode(body: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Select,
      undefined,
      this.makePtrFields(body),
    );
  }

  public CreateCaseNode(expression: NodeId, body: NodeId[]): Node {
    return this.createIndexed(go.Opcode.Case, undefined, [
      this.makePtr(expression),
      ...this.makePtrFields(body),
    ]);
  }

  public CreateDefaultNode(body: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Default,
      undefined,
      this.makePtrFields(body),
    );
  }

  /**
   * Creates an addition expression (`a + b`).
   *
   * @example
   * ```ts
   * const addId = builder.SetNode(
   *   builder.CreateAddNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x + y
   * ```
   */
  public CreateAddNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Add, a, b);
  }

  /**
   * Creates a subtraction expression (`a - b`).
   *
   * @example
   * ```ts
   * const subId = builder.SetNode(
   *   builder.CreateSubNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x - y
   * ```
   */
  public CreateSubNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Sub, a, b);
  }

  /**
   * Creates a multiplication expression (`a * b`).
   *
   * @example
   * ```ts
   * const mulId = builder.SetNode(
   *   builder.CreateMulNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x * y
   * ```
   */
  public CreateMulNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Mul, a, b);
  }

  /**
   * Creates a division expression (`a / b`).
   *
   * @example
   * ```ts
   * const divId = builder.SetNode(
   *   builder.CreateDivNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x / y
   * ```
   */
  public CreateDivNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Div, a, b);
  }

  /**
   * Creates a modulo expression (`a % b`).
   *
   * @example
   * ```ts
   * const modId = builder.SetNode(
   *   builder.CreateModNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x % y
   * ```
   */
  public CreateModNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Mod, a, b);
  }

  /**
   * Creates an increment operation (`a++`).
   *
   * @example
   * ```ts
   * const incId = builder.SetNode(
   *   builder.CreateIncNode(xId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x++
   * ```
   */
  public CreateIncNode(a: string | NodeId): Node {
    return this.createUnary(go.Opcode.Inc, a);
  }

  /**
   * Creates a decrement operation (`a--`).
   *
   * @example
   * ```ts
   * const decId = builder.SetNode(
   *   builder.CreateDecNode(xId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x--
   * ```
   */
  public CreateDecNode(a: string | NodeId): Node {
    return this.createUnary(go.Opcode.Dec, a);
  }

  /**
   * Creates an assignment (`a = b`).
   *
   * @example
   * ```ts
   * const assignId = builder.SetNode(
   *   builder.CreateAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x = y
   * ```
   */
  public CreateAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Assign, a, b);
  }

  /**
   * Creates an addition assignment (`a += b`).
   *
   * @example
   * ```ts
   * const addAssignId = builder.SetNode(
   *   builder.CreateAddAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x += y
   * ```
   */
  public CreateAddAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.AddAssign, a, b);
  }

  /**
   * Creates a subtraction assignment (`a -= b`).
   *
   * @example
   * ```ts
   * const subAssignId = builder.SetNode(
   *   builder.CreateSubAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x -= y
   * ```
   */
  public CreateSubAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.SubAssign, a, b);
  }

  /**
   * Creates a multiplication assignment (`a *= b`).
   *
   * @example
   * ```ts
   * const mulAssignId = builder.SetNode(
   *   builder.CreateMulAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x *= y
   * ```
   */
  public CreateMulAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.MulAssign, a, b);
  }

  /**
   * Creates a division assignment (`a /= b`).
   *
   * @example
   * ```ts
   * const divAssignId = builder.SetNode(
   *   builder.CreateDivAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x /= y
   * ```
   */
  public CreateDivAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.DivAssign, a, b);
  }

  /**
   * Creates a modulo assignment (`a %= b`).
   *
   * @example
   * ```ts
   * const modAssignId = builder.SetNode(
   *   builder.CreateModAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x %= y
   * ```
   */
  public CreateModAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.ModAssign, a, b);
  }

  /**
   * Creates a bitwise AND assignment (`a &= b`).
   *
   * @example
   * ```ts
   * const andAssignId = builder.SetNode(
   *   builder.CreateBitAndAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x &= y
   * ```
   */
  public CreateBitAndAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitAndAssign, a, b);
  }

  /**
   * Creates a bitwise OR assignment (`a |= b`).
   *
   * @example
   * ```ts
   * const orAssignId = builder.SetNode(
   *   builder.CreateBitOrAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x |= y
   * ```
   */
  public CreateBitOrAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitOrAssign, a, b);
  }

  /**
   * Creates a bitwise XOR assignment (`a ^= b`).
   *
   * @example
   * ```ts
   * const xorAssignId = builder.SetNode(
   *   builder.CreateBitXorAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x ^= y
   * ```
   */
  public CreateBitXorAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitXorAssign, a, b);
  }

  /**
   * Creates a bit clear assignment (`a &^= b`).
   *
   * @example
   * ```ts
   * const clearAssignId = builder.SetNode(
   *   builder.CreateBitClearAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x &^= y
   * ```
   */
  public CreateBitClearAssignNode(
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return this.createBinary(go.Opcode.BitClearAssign, a, b);
  }

  /**
   * Creates a left shift assignment (`a <<= b`).
   *
   * @example
   * ```ts
   * const shiftAssignId = builder.SetNode(
   *   builder.CreateLeftShiftAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x <<= y
   * ```
   */
  public CreateLeftShiftAssignNode(
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return this.createBinary(go.Opcode.LeftShiftAssign, a, b);
  }

  /**
   * Creates a right shift assignment (`a >>= b`).
   *
   * @example
   * ```ts
   * const shiftAssignId = builder.SetNode(
   *   builder.CreateRightShiftAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x >>= y
   * ```
   */
  public CreateRightShiftAssignNode(
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return this.createBinary(go.Opcode.RightShiftAssign, a, b);
  }

  /**
   * Creates an equality comparison (`a == b`).
   *
   * @example
   * ```ts
   * const eqId = builder.SetNode(
   *   builder.CreateEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x == y
   * ```
   */
  public CreateEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Equal, a, b);
  }

  /**
   * Creates an inequality comparison (`a != b`).
   *
   * @example
   * ```ts
   * const neId = builder.SetNode(
   *   builder.CreateNotEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x != y
   * ```
   */
  public CreateNotEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.NotEqual, a, b);
  }

  /**
   * Creates a less-than comparison (`a < b`).
   *
   * @example
   * ```ts
   * const ltId = builder.SetNode(
   *   builder.CreateLessNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x < y
   * ```
   */
  public CreateLessNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Less, a, b);
  }

  /**
   * Creates a less-than-or-equal comparison (`a <= b`).
   *
   * @example
   * ```ts
   * const leId = builder.SetNode(
   *   builder.CreateLessEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x <= y
   * ```
   */
  public CreateLessEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.LessEqual, a, b);
  }

  /**
   * Creates a greater-than comparison (`a > b`).
   *
   * @example
   * ```ts
   * const gtId = builder.SetNode(
   *   builder.CreateGreaterNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x > y
   * ```
   */
  public CreateGreaterNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Greater, a, b);
  }

  /**
   * Creates a greater-than-or-equal comparison (`a >= b`).
   *
   * @example
   * ```ts
   * const geId = builder.SetNode(
   *   builder.CreateGreaterEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x >= y
   * ```
   */
  public CreateGreaterEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.GreaterEqual, a, b);
  }

  /**
   * Creates a logical AND (`a && b`).
   *
   * @example
   * ```ts
   * const andId = builder.SetNode(
   *   builder.CreateAndNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x && y
   * ```
   */
  public CreateAndNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.And, a, b);
  }

  /**
   * Creates a logical OR (`a || b`).
   *
   * @example
   * ```ts
   * const orId = builder.SetNode(
   *   builder.CreateOrNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x || y
   * ```
   */
  public CreateOrNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Or, a, b);
  }

  /**
   * Creates a logical NOT (`!a`).
   *
   * @example
   * ```ts
   * const notId = builder.SetNode(
   *   builder.CreateNotNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * !x
   * ```
   */
  public CreateNotNode(a: string | NodeId): Node {
    return this.createUnary(go.Opcode.Not, a);
  }

  /**
   * Creates a bitwise AND (`a & b`).
   *
   * @example
   * ```ts
   * const bitAndId = builder.SetNode(
   *   builder.CreateBitAndNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x & y
   * ```
   */
  public CreateBitAndNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitAnd, a, b);
  }

  /**
   * Creates a bitwise OR (`a | b`).
   *
   * @example
   * ```ts
   * const bitOrId = builder.SetNode(
   *   builder.CreateBitOrNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x | y
   * ```
   */
  public CreateBitOrNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitOr, a, b);
  }

  /**
   * Creates a bitwise XOR (`a ^ b`).
   *
   * @example
   * ```ts
   * const xorId = builder.SetNode(
   *   builder.CreateBitXorNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x ^ y
   * ```
   */
  public CreateBitXorNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitXor, a, b);
  }

  /**
   * Creates a bit clear (`a &^ b`).
   *
   * @example
   * ```ts
   * const clearId = builder.SetNode(
   *   builder.CreateBitClearNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x &^ y
   * ```
   */
  public CreateBitClearNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitClear, a, b);
  }

  /**
   * Creates a left shift (`a << b`).
   *
   * @example
   * ```ts
   * const shiftId = builder.SetNode(
   *   builder.CreateLeftShiftNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x << y
   * ```
   */
  public CreateLeftShiftNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.LeftShift, a, b);
  }

  /**
   * Creates a right shift (`a >> b`).
   *
   * @example
   * ```ts
   * const shiftId = builder.SetNode(
   *   builder.CreateRightShiftNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x >> y
   * ```
   */
  public CreateRightShiftNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.RightShift, a, b);
  }

  /** ch <- value */
  public CreateChanSendNode(chan: NodeId, value: NodeId): Node {
    return this.createBinary(go.Opcode.Send, chan, value);
  }

  /** <-ch */
  public CreateChanReceiveNode(chan: NodeId): Node {
    return this.createUnary(go.Opcode.Receive, chan);
  }

  /**
   * Creates an address-of expression (`&a`).
   *
   * @example
   * ```ts
   * const addrId = builder.SetNode(
   *   builder.CreateAddrOfNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * &x
   * ```
   */
  public CreateAddrOfNode(value: NodeId): Node {
    return this.createUnary(go.Opcode.AddrOf, value);
  }

  /**
   * Dereferences a pointer (`*ptr`).
   *
   * @example
   * ```ts
   * const ptrId = builder.SetNode(
   *   builder.CreateDerefNode(ptr)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * *ptr
   * ```
   */
  public CreateDerefNode(ptr: NodeId): Node {
    return this.createUnary(go.Opcode.Deref, ptr);
  }

  /**
   * Represents a function or method call.
   *
   * @param funcId Function name or selector
   * @param params Arguments (literals or {@link NodeId}s)
   *
   * @example
   * ```ts
   * const callId = builder.SetNode(
   *   builder.CreateCallNode("fmt.Println", ["Hello, world!"])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * fmt.Println("Hello, world!")
   * ```
   */
  public CreateCallNode(funcId: string, params: (NodeId | string)[]): Node {
    return this.createIndexed(
      go.Opcode.Call,
      funcId,
      params.map((v) => this.makeValue(v)),
    );
  }

  /**
   * Creates a `return` statement.
   *
   * Each NodeId in `params` represents an expression to be returned.
   * An empty array represents a bare `return`.
   *
   * @example
   * ```ts
   * const aId = builder.SetNode(
   *   builder.CreateVarValueNode("a", intType, "0")
   * );
   * const bId = builder.SetNode(
   *   builder.CreateVarValueNode("b", intType, "0")
   * );
   *
   * const returnId = builder.SetNode(
   *   builder.CreateReturnNode([ aId, bId ])
   * );
   *
   * builder.ConnectNodes(funcId, returnId);
   *```
   *
   * Compiler output:
   * ```go
   * return a, b
   * ```
   */
  public CreateReturnNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Return,
      undefined,
      this.makePtrFields(params),
    );
  }

  /**
   * Creates a `defer` statement.
   *
   * The operand MUST be a call node.
   *
   * @example
   * ```ts
   * const callId = builder.SetNode(
   *   builder.CreateCallNode("fmt.Println", ["Hello, world!"])
   * );
   *
   * const deferId = builder.SetNode(
   *   builder.CreateDeferNode(callId)
   * );
   *
   * builder.ConnectNodes(funcId, deferId);
   * ```
   *
   * Compiler output:
   * ```go
   * defer fmt.Println("Hello, world!")
   * ```
   */
  public CreateDeferNode(call: NodeId): Node {
    return this.createUnary(go.Opcode.Defer, call);
  }

  /**
   * Creates a goroutine invocation
   *
   * @example
   * ```ts
   * const callId = builder.SetNode(
   *   builder.CreateCallNode("worker", [])
   * );
   *
   * const goId = builder.SetNode(
   *   builder.CreateGoRoutineNode(callId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * go worker()
   * ```
   * */
  public CreateGoRoutineNode(call: NodeId): Node {
    return this.createUnary(go.Opcode.GoRoutine, call);
  }

  // public CreateMapNode(mapDef: TypeDef, body: NodeId[]): Node {
  //   // WARN - needs attention
  //   // return this.createIndexed(go.Opcode.Map, undefined, this.makePtrFields(body));
  // }

  // public CreateArrayNode(arrayDef: TypeDef, body: NodeId[]): Node {
  //   // WARN - needs attention
  //   // return this.createIndexed(go.Opcode.Array, undefined, this.makePtrFields(body));
  // }

  /**
   * Creates a panic call.
   *
   * @example
   * ```ts
   * const panicId = builder.SetNode(
   *   builder.Panic(xId)
   * );
   * ```
   *
   * ```go
   * panic(x)
   * ```
   */
  public Panic(expression: NodeId): Node {
    return this.createUnary(go.Opcode.Panic, expression);
  }

  /**
   * Creates a `recover()` builtin call
   */
  public Recover(): Node {
    return {
      opcode: go.Opcode.Recover,
      flags: go.NodeFlag.None,
    };
  }

  /**
   * Creates a `make` builtin call.
   *
   * @example
   * ```ts
   * const makeId = builder.SetNode(
   *   builder.CreateMakeNode([sliceTypeId])
   * );
   * ```
   *
   * ```go
   * make([]int)
   * ```
   */
  public CreateMakeNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Make,
      undefined,
      this.makePtrFields(params),
    );
  }

  /**
   * Allocates a new value.
   *
   * @example
   * ```ts
   * const newId = builder.SetNode(
   *   builder.New(myType)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * new(T)
   * ```
   */
  public New(_type: GoType): Node {
    return this.createUnary(go.Opcode.New, 0n);
  }

  /**
   * Gets the length of a value (`len(x)`).
   *
   * For slices, this is the number of elements currently in use.
   *
   * @example
   * ```ts
   * const lenId = builder.SetNode(
   *   builder.CreateLenNode(sliceId)
   * );
   * ```
   *
   * ```go
   * len(slice)
   * ```
   */
  public CreateLenNode(param: NodeId): Node {
    return this.createUnary(go.Opcode.Len, param);
  }

  /**
   * Returns the capacity of a value `cap(x)`.
   *
   * For slices, this is the maximum size before reallocation.
   *
   * @example
   * ```ts
   * const capId = builder.SetNode(
   *   builder.CreateCapNode(sliceId)
   * );
   * ```
   *
   * ```go
   * cap(slice)
   * ```
   */
  public CreateCapNode(param: NodeId): Node {
    return this.createUnary(go.Opcode.Cap, param);
  }

  /**
   * Appends values to a slice.
   *
   * @example
   * ```ts
   * const appendId = builder.SetNode(
   *   builder.CreateAppendNode([sliceId, valueId])
   * );
   * ```
   *
   * ```go
   * append(slice, value)
   * ```
   */
  public CreateAppendNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Append,
      undefined,
      this.makePtrFields(params),
    );
  }

  /**
   * Copies elements between slices.
   *
   * @example
   * ```ts
   * const copyId = builder.SetNode(
   *   builder.CreateCopyNode(dstId, srcId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * copy(dst, src)
   * ```
   */
  public CreateCopyNode(dst: NodeId, src: NodeId): Node {
    return this.createBinary(go.Opcode.Copy, dst, src);
  }

  /**
   * Closes a channel.
   *
   * @example
   * ```ts
   * const closeId = builder.SetNode(
   *   builder.CreateCloseNode(chanType)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * close(ch)
   * ```
   */
  public CreateCloseNode(chan: GoType): Node {
    // WARN - NEEDS ATTENTION
    return this.createUnary(go.Opcode.Close, 0n);
  }

  public CreateComplexNode(r: string, i: string): Node {
    return this.createBinary(go.Opcode.Complex, r, i);
  }

  public CreateRealNode(c: NodeId): Node {
    return this.createUnary(go.Opcode.Real, c);
  }

  public CreateImagNode(c: NodeId): Node {
    return this.createUnary(go.Opcode.Imag, c);
  }

  public CreatePrintNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Print,
      undefined,
      this.makePtrFields(params),
    );
  }

  public CreatePrintlnNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Println,
      undefined,
      this.makePtrFields(params),
    );
  }

  private SerializeType(t: GoTypeDef): fb.Offset {
    let typeOffset: fb.Offset = 0;
    let typeEnum = program.Type.NONE;
    let base: go.Kind = go.Kind.Nil;
    let basePtr: boolean = false;
    let flags: number = 0;
    switch (t.base) {
      case GoKind.FUNC:
        typeOffset = this.CreateFuncType(t as GoFunctionType);
        //typeEnum = program.Type.FunctionType;
        break;
      case GoKind.SLICE:
      case GoKind.ARRAY:
        typeOffset = this.CreateArrayType(t as GoArrayType);
        //typeEnum = program.Type.ArrayType;
        break;
      case GoKind.MAP:
        typeOffset = this.CreateMapType(t as GoMapType);
        //typeEnum = program.Type.MapType;
        break;
      case GoKind.INTERFACE:
        typeOffset = this.CreateInterfaceType(t as GoInterfaceType);
        //typeEnum = program.Type.StructureType;
        break;
      case GoKind.STRUCT:
        typeOffset = this.CreateStructType(t as GoStructType);
        //typeEnum = program.Type.StructureType;
        break;
      case GoKind.POINTER:
        typeOffset = this.CreatePointerType(t as GoPointerType);
        //typeEnum = program.Type.PointerType;
        break;
      case GoKind.BOOLEAN:
      case GoKind.CHANNEL:
      case GoKind.BYTE:
      case GoKind.COMPLEX128:
      case GoKind.COMPLEX64:
      case GoKind.FLOAT32:
      case GoKind.FLOAT64:
      case GoKind.INT:
      case GoKind.INT16:
      case GoKind.INT32:
      case GoKind.INT64:
      case GoKind.INT8:
      case GoKind.RUNE:
      case GoKind.STRING:
      //case GoKind.UINT:
      case GoKind.UINT16:
      case GoKind.UINT32:
      case GoKind.UINT64:
      case GoKind.UINT8:
      case GoKind.UINTPTR:
        break;
      default:
        basePtr = true;
        const baseResult = this.typelut.findIndex((v) => v.id == t.base);
        if (baseResult == -1)
          throw Error(
            `type ${t.id} requires a valid base type. Type must be set before inheritance.`,
          );
        base = baseResult;
    }

    if (!basePtr) {
      base = KindMapper(t.base as GoKind);
    }

    program.TypeDef.startTypeDef(this.builder);
    program.TypeDef.addBase(this.builder, base);
    program.TypeDef.addId(this.builder, this.SetString(t.id));
    program.TypeDef.addTypeType(this.builder, typeEnum);
    program.TypeDef.addType(this.builder, typeOffset);
    program.TypeDef.addFlags(this.builder, flags);

    return program.TypeDef.endTypeDef(this.builder);
  }

  public SetType(t: GoTypeDef): number {
    // check if type already exists
    let uid = this.typelut.findIndex((v) => v && v.id === t.id);
    if (uid >= 0) return uid;

    // otherwise, create the type and push it
    const addr = this.SerializeType(t);

    uid = this.nextTypeId++ >>> 0;
    if (uid > 0xfffffffe) throw new Error("uint32 overflow");

    this.typelut[uid] = {
      id: t.id,
      addr,
    };

    return uid;
  }

  private CreateFuncType(func: GoFunctionType): fb.Offset {
    /*let impl: fb.Offset = 0;

    if (func.impl)
      impl = program.Pair.createPair(
        this.builder,
        this.SetString(func.impl[0]),
        this.SetType(func.impl[1]),
      );

    let typeSig: fb.Offset = 0;
    if (func.typeSig) typeSig = this.SetType(func.typeSig);*/

    let paramsList: fb.Offset[] = [];
    for (const [val, ty] of func.params) {
      /*paramsList.push(
        program.Pair.createPair(
          this.builder,
          this.SetString(val),
          this.SetType(ty),
        ),
      );*/
    }

    const params = go.GoType.createParamsVector(
      this.builder,
      [],
    );

    let resultsList: fb.Offset[] = [];
    for (const [val, ty] of func.results) {
      /*resultsList.push(
        program.Pair.createPair(
          this.builder,
          this.SetString(val),
          this.SetType(ty),
        ),
      );*/
    }
    const results = go.GoType.createResultsVector(
      this.builder,
      [],
    );

    go.GoType.startGoType(this.builder);
    go.GoType.addParams(this.builder, params);
    go.GoType.addResults(this.builder, results);
    //go.GoType.addImpl(this.builder, impl);
    //go.GoType.addTypeSig(this.builder, typeSig);

    return go.GoType.endGoType(this.builder);
  }

  private CreateArrayType(arr: GoArrayType): fb.Offset {
    const size = packIntArrayToBigInt(arr.size, 64 / arr.size.length);

    const elem = this.SetType(arr.elem);

    go.GoType.startGoType(this.builder);
    go.GoType.addSize(this.builder, size);
    go.GoType.addElem(this.builder, elem);

    return go.GoType.endGoType(this.builder);
  }

  private CreateMapType(map: GoMapType): fb.Offset {
    const key = this.SetType(map.key);
    const value = this.SetType(map.value);

    go.GoType.startGoType(this.builder);
    go.GoType.addKey(this.builder, key);
    go.GoType.addValue(this.builder, value);

    return go.GoType.endGoType(this.builder);
  }

  private CreateStructType(struct: GoStructType): fb.Offset {
    const fields: fb.Offset[] = [];
    for (const field of struct.fields) {
      const name = this.SetString(field.name);
      const _type = this.SetType(field.type);

      go.StructField.startStructField(this.builder);
      go.StructField.addName(this.builder, name);
      go.StructField.addType(this.builder, _type);
      if (field.tag)
        go.StructField.addMisc(this.builder, this.SetString(field.tag));
      fields.push(go.StructField.endStructField(this.builder));
    }

    const fieldsOffset = go.GoType.createFieldsVector(
      this.builder,
      fields,
    );

    go.GoType.startGoType(this.builder);
    go.GoType.addFields(this.builder, fieldsOffset);
    
    return go.GoType.endGoType(this.builder);
  }

  private CreateInterfaceType(_interface: GoInterfaceType): fb.Offset {
    const methods: number[] = [];
    for (const method of _interface.methods) {
      const _type = this.SetType(method);
      methods.push(_type);
    }

    const methodsOffset = go.GoType.createMethodsVector(
      this.builder,
      [],
    );

    go.GoType.startGoType(this.builder);
    go.GoType.addMethods(this.builder, methodsOffset);
    
    return go.GoType.endGoType(this.builder);
  }

  private CreatePointerType(ptr: GoPointerType): fb.Offset {
    const _type = this.SetType(ptr.elem);
    go.GoType.startGoType(this.builder);
    go.GoType.addElem(this.builder, _type);

    return go.GoType.endGoType(this.builder);
  }

  private buildNodeValue(v: GoNodeValue): fb.Offset {
    let typeHash: number | undefined;
    if (v.type !== undefined) {
      typeHash = this.SetType(v.type);
    }

    let valueOffset: NodeId;
    if (typeof v.value === "string") {
      valueOffset = BigInt(this.SetString(v.value));
    } else valueOffset = v.value ?? 0n;

    program.NodeValue.startNodeValue(this.builder);

    if (typeHash !== void 0) {
      program.NodeValue.addType(this.builder, typeHash);
    }

    program.NodeValue.addValue(this.builder, valueOffset);
    program.NodeValue.addFlags(this.builder, v.flags);
    return program.NodeValue.endNodeValue(this.builder);
  }

  private CreateIndexedNode(node: Node): fb.Offset {
    const fields = node.fields?.map((v) => this.buildNodeValue(v)) ?? [];
    const fieldsVector = program.IndexedNode.createFieldsVector(
      this.builder,
      fields,
    );

    program.IndexedNode.startIndexedNode(this.builder);
    program.IndexedNode.addId(this.builder, node.id ?? 0);
    program.IndexedNode.addFields(this.builder, fieldsVector);

    return program.IndexedNode.endIndexedNode(this.builder);
  }

  private CreateBinaryNode(node: Node): fb.Offset {
    let left: fb.Offset = 0;
    let right: fb.Offset = 0;

    if (node.left) {
      left = this.buildNodeValue(node.left);
    }

    if (node.right) {
      right = this.buildNodeValue(node.right);
    }

    program.BinaryNode.startBinaryNode(this.builder);
    program.BinaryNode.addLeft(this.builder, left);
    program.BinaryNode.addRight(this.builder, right);
    return program.BinaryNode.endBinaryNode(this.builder);
  }

  private CreateUnaryNode(node: Node): fb.Offset {
    let value: fb.Offset = 0;
    if (node.value) {
      value = this.buildNodeValue(node.value);
    }

    program.UnaryNode.startUnaryNode(this.builder);
    program.UnaryNode.addValue(this.builder, value);
    return program.UnaryNode.endUnaryNode(this.builder);
  }

  // Initiates a data stream between the recipitant and the end user
  // Use this to feed the compiler the data live
  public Hook(addr: string) {}
}
