import {
  NodeId,
  BuilderOptions,
  IBuilder,
  INode,
  INodeValue
} from "../ibuilder";
import * as fb from "flatbuffers";
import * as go from "./golang";
import * as program from "../program";

import {
  GoArrayType,
  GoFunctionType,
  GoInterfaceType,
  GoKind,
  GoMapType,
  GoPointerType,
  GoStruct,
  GoStructType,
  GoType,
  GoTypeDef,
  KindMapper,
} from "./types";
import { packIntArrayToBigInt } from "./utils";

export interface FuncImpl {
  type: GoTypeDef; // Must be of GoFuncType
  params?: NodeId[]; // Input parameters
  body?: NodeId[]; // Array of node id
}

export interface GoNodeValue extends INodeValue {
  type?: GoTypeDef;
}

export interface Node extends INode<go.Opcode, GoNodeValue> {}

export interface GoBuilderOptions extends BuilderOptions {}

/**
 * Go-specific implementation of the generic builder.
 *
 * The Go source code is generated by a separate compiler.
 */
export class GoBuilder extends IBuilder<go.Opcode, go.NodeFlag, go.ValueFlag> {

  protected buildNode(node: Node, id: NodeId): fb.Offset {
    let nodeType = program.NodeUnion.NONE;
    let nodeContentOffset: fb.Offset = 0;
    switch (node.flags) {
      case go.NodeFlag.NodeIndexed:
        nodeType = program.NodeUnion.IndexedNode;
        nodeContentOffset = this.CreateIndexedNode(node);
        break;
      case go.NodeFlag.NodeBinary:
        nodeType = program.NodeUnion.BinaryNode;
        nodeContentOffset = this.CreateBinaryNode(node);
        break;
      case go.NodeFlag.NodeUnary:
        nodeType = program.NodeUnion.UnaryNode;
        nodeContentOffset = this.CreateUnaryNode(node);
        break;
    }

    program.Node.startNode(this.builder);
    program.Node.addOpcode(this.builder, node.opcode);

    //console.log("Node id:", id);
    program.Node.addId(this.builder, id);
    program.Node.addParent(this.builder, node.parent ?? 0n);
    program.Node.addNext(this.builder, node.next ?? 0n);
    program.Node.addFlags(this.builder, node.flags);
    program.Node.addNodeType(this.builder, nodeType);
    program.Node.addNode(this.builder, nodeContentOffset);
    return program.Node.endNode(this.builder);
  }


  public CreateNode(opcode: go.Opcode, flags: number): Node {
    return {
      opcode,
      flags,
    };
  }

  private isValidNumber(str: string): boolean {
    return !isNaN(Number(str));
  }

  private makeValue(v: string | NodeId, t?: GoTypeDef): GoNodeValue {
    let flags: number;

    if (typeof v === "bigint") {
      flags = go.ValueFlag.Pointer;
    } else {
      flags = this.isValidNumber(v)
        ? go.ValueFlag.None
        : go.ValueFlag.Quotation;
    }

    return { type: t, value: v, flags };
  }

  private makePtr(v: NodeId): GoNodeValue {
    return {
      value: v,
      flags: go.ValueFlag.Pointer,
    };
  }

  private makePtrFields(values: NodeId[]): GoNodeValue[] {
    return values.map((v) => this.makePtr(v));
  }

  private createUnary(opcode: go.Opcode, a: string | NodeId): Node {
    return {
      opcode,
      flags: go.NodeFlag.NodeUnary,

      value: this.makeValue(a),
    };
  }

  private createBinary(
    opcode: go.Opcode,
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return {
      opcode,
      flags: go.NodeFlag.NodeBinary,

      left: this.makeValue(a),
      right: this.makeValue(b),
    };
  }

  private createIndexed(
    opcode: go.Opcode,
    id?: string,
    fields?: GoNodeValue[],
  ): Node {
    let idOffset: fb.Offset | undefined;
    if (id !== void 0) {
      idOffset = this.SetString(id);
    };

    return {
      opcode,
      flags: go.NodeFlag.NodeIndexed,

      id: idOffset,
      fields,
    };
  }

  /**
   * Creates a Go package declaration.
   *
   * @example
   * ```ts
   * const pkgId = builder.SetNode(
   *   builder.CreatePackageNode("main")
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * package main
   * ```
   */
  public CreatePackageNode(id: string): Node {
    if (id.trim().length <= 0)
      throw new Error("Package name must be non-empty");

    // TODO: Add regex check to evaluate if id is valid

    return this.createIndexed(go.Opcode.Package, id);
  }

  /**
   * Creates an import block.
   *
   * @example
   * ```ts
   * const fmtId = builder.SetNode(
   *   builder.CreateImportValueNode("fmt")
   * );
   *
   * const httpId = builder.SetNode(
   *   builder.CreateImportValueNode("net/http", "http")
   * );
   *
   * const importId = builder.SetNode(
   *   builder.CreateImportNode(fmtId, httpId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * import (
   *   "fmt"
   *   http "net/http"
   * )
   * ```
   */
  public CreateImportNode(...imports: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Import,
      undefined,
      this.makePtrFields(imports),
    );
  }

  public CreateImportValueNode(path: string, alias?: string): Node {
    return this.createBinary(go.Opcode.ImportValue, alias ?? "", path);
  }

  /**
   * Creates a constant declaration.
   *
   * @example
   * ```ts
   * const piId = builder.SetNode(
   *   builder.CreateConstValueNode("pi", floatType, "3.14")
   * );
   *
   * const constId = builder.SetNode(
   *   builder.CreateConstNode(piId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * const pi = 3.14
   * ```
   */
  public CreateConstNode(...constants: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Const,
      undefined,
      this.makePtrFields(constants),
    );
  }

  public CreateConstValueNode(
    name: string,
    type: GoTypeDef,
    value: string,
  ): Node {
    return {
      opcode: go.Opcode.ConstValue,
      flags: go.NodeFlag.NodeBinary,

      left: this.makeValue(name, type),
      right: this.makeValue(value),
    };
  }

  /**
   * Creates a variable declaration.
   *
   * @example
   * ```ts
   * const xId = builder.SetNode(
   *   builder.CreateVarValueNode("x", intType, "0")
   * );
   *
   * const varId = builder.SetNode(
   *   builder.CreateVarNode(xId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * var x = 0
   * ```
   */
  public CreateVarNode(...vars: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Var,
      undefined,
      this.makePtrFields(vars),
    );
  }

  public CreateVarValueNode(
    name: string,
    type: GoTypeDef,
    value: string,
  ): Node {
    return {
      opcode: go.Opcode.VarValue,
      flags: go.NodeFlag.NodeBinary,

      left: this.makeValue(name, type),
      right: this.makeValue(value),
    };
  }

  /**
   * Creates a type declaration.
   *
   * @example
   * ```ts
   * const typeId = builder.SetNode(
   *   builder.CreateTypeNode(myStructType)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * type MyStruct struct { ... }
   * ```
   */
  public CreateTypeNode(type: GoTypeDef): Node {
    return this.createIndexed(go.Opcode.Type, type.id, [
      {
        type,
        value: 0n,
        flags: go.ValueFlag.None,
      },
    ]);
  }

  /**
   * Creates a `func` node.
   *
   * The function signature is defined by `type`.
   * Parameters and body are referenced via {@link NodeId}s and
   * stored as indexed fields with semantic flags.
   *
   * Compiler output:
   * ```go
   * func main() {}
   * ```
   */
  public CreateFuncNode(def: FuncImpl): Node {
    const meta: GoNodeValue = {
      type: def.type,
      value: 0n,
      flags: go.ValueFlag.FuncMeta,
    };

    const params =
      def.params?.map((v) => ({
        value: v,
        flags: go.ValueFlag.Pointer | go.ValueFlag.FuncParam,
      })) ?? [];

    const body =
      def.body?.map((v) => ({
        value: v,
        flags: go.ValueFlag.Pointer | go.ValueFlag.FuncBody, // WARN - Add proper value flag definition
      })) ?? [];

    return this.createIndexed(go.Opcode.Func, def.type.id, [
      meta,
      ...params,
      ...body,
    ]);
  }

  /**
   * Creates an if / else statement.
   *
   * @example
   * ```ts
   * const condId = builder.SetNode(
   *   builder.CreateGreaterNode(xId, yId)
   * );
   *
   * const ifId = builder.SetNode(
   *   builder.CreateIfNode(condId, [ thenStmtId ], [ elseStmtId ])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * if x > y {
   *   ...
   * } else {
   *   ...
   * }
   * ```
   */
  public CreateIfNode(
    condition: NodeId,
    body: NodeId[],
    _else: NodeId[] = [],
  ): Node {
    return this.createIndexed(go.Opcode.If, undefined, [
      {
        value: condition,
        flags: go.ValueFlag.Pointer | go.ValueFlag.IfConditon, // WARN - Add proper value flag definition
      },
      ...body.map((v) => {
        return {
          value: v,
          flags: go.ValueFlag.Pointer | go.ValueFlag.IfBody, // WARN - Add proper value flag definition
        };
      }),
      ..._else.map((v) => {
        return {
          value: v,
          flags: go.ValueFlag.Pointer | go.ValueFlag.IfElse, // WARN - Add proper value flag definition
        };
      }),
    ]);
  }

  /**
   * Creates a classic for-loop.
   *
   * @example
   * ```ts
   * const forId = builder.SetNode(
   *   builder.CreateForNode(initId, condId, postId, bodyIds)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * for init; cond; post {
   *   ...
   * }
   * ```
   */
  public CreateForNode(
    init: NodeId,
    cond: NodeId,
    post: NodeId,
    body: NodeId[],
  ): Node {
    return this.createIndexed(go.Opcode.For, undefined, [
      this.makePtr(init),
      this.makePtr(cond),
      this.makePtr(post),
      ...this.makePtrFields(body),
    ]);
  }

  /**
   * Creates a range-based for loop.
   *
   * @example
   * ```ts
   * const rangeId = builder.SetNode(
   *   builder.CreateForRangeNode(keyId, valueId, sliceId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * for k, v := range slice {
   *   ...
   * }
   * ```
   */
  public CreateForRangeNode(
    var1: NodeId, // First variable assignment
    var2: NodeId, // Second varable assignment
    value: NodeId, // Ranged value
  ): Node {
    return this.createIndexed(go.Opcode.ForRange, undefined, [
      this.makePtr(var1),
      this.makePtr(var2),
      this.makePtr(value),
    ]);
  }

  /**
   * Creates a switch statement.
   *
   * @example
   * ```ts
   * const switchId = builder.SetNode(
   *   builder.CreateSwitchNode(exprId, [ caseId, defaultId ])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * switch expr {
   * case x:
   *   ...
   * default:
   *   ...
   * }
   * ```
   */
  public CreateSwitchNode(expression: NodeId, body: NodeId[]): Node {
    return this.createIndexed(go.Opcode.Switch, undefined, [
      /*this.makePtr(expression),*/ ...this.makePtrFields(body),
    ]);
  }

  /**
   * Creates a select statement.
   *
   * @example
   * ```ts
   * const selectId = builder.SetNode(
   *   builder.CreateSelectNode([ caseId ])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * select {
   * case <-ch:
   *   ...
   * }
   * ```
   */
  public CreateSelectNode(body: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Select,
      undefined,
      this.makePtrFields(body),
    );
  }

  public CreateCaseNode(expression: NodeId, body: NodeId[]): Node {
    return this.createIndexed(go.Opcode.Case, undefined, [
      this.makePtr(expression),
      ...this.makePtrFields(body),
    ]);
  }

  public CreateDefaultNode(body: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Default,
      undefined,
      this.makePtrFields(body),
    );
  }

  /**
   * Creates an addition expression (`a + b`).
   *
   * @example
   * ```ts
   * const addId = builder.SetNode(
   *   builder.CreateAddNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x + y
   * ```
   */
  public CreateAddNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Add, a, b);
  }

  /**
   * Creates a subtraction expression (`a - b`).
   *
   * @example
   * ```ts
   * const subId = builder.SetNode(
   *   builder.CreateSubNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x - y
   * ```
   */
  public CreateSubNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Sub, a, b);
  }

  /**
   * Creates a multiplication expression (`a * b`).
   *
   * @example
   * ```ts
   * const mulId = builder.SetNode(
   *   builder.CreateMulNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x * y
   * ```
   */
  public CreateMulNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Mul, a, b);
  }

  /**
   * Creates a division expression (`a / b`).
   *
   * @example
   * ```ts
   * const divId = builder.SetNode(
   *   builder.CreateDivNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x / y
   * ```
   */
  public CreateDivNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Div, a, b);
  }

  /**
   * Creates a modulo expression (`a % b`).
   *
   * @example
   * ```ts
   * const modId = builder.SetNode(
   *   builder.CreateModNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x % y
   * ```
   */
  public CreateModNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Mod, a, b);
  }

  /**
   * Creates an increment operation (`a++`).
   *
   * @example
   * ```ts
   * const incId = builder.SetNode(
   *   builder.CreateIncNode(xId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x++
   * ```
   */
  public CreateIncNode(a: string | NodeId): Node {
    return this.createUnary(go.Opcode.Inc, a);
  }

  /**
   * Creates a decrement operation (`a--`).
   *
   * @example
   * ```ts
   * const decId = builder.SetNode(
   *   builder.CreateDecNode(xId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x--
   * ```
   */
  public CreateDecNode(a: string | NodeId): Node {
    return this.createUnary(go.Opcode.Dec, a);
  }

  /**
   * Creates an assignment (`a = b`).
   *
   * @example
   * ```ts
   * const assignId = builder.SetNode(
   *   builder.CreateAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x = y
   * ```
   */
  public CreateAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Assign, a, b);
  }

  /**
   * Creates an addition assignment (`a += b`).
   *
   * @example
   * ```ts
   * const addAssignId = builder.SetNode(
   *   builder.CreateAddAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x += y
   * ```
   */
  public CreateAddAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.AddAssign, a, b);
  }

  /**
   * Creates a subtraction assignment (`a -= b`).
   *
   * @example
   * ```ts
   * const subAssignId = builder.SetNode(
   *   builder.CreateSubAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x -= y
   * ```
   */
  public CreateSubAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.SubAssign, a, b);
  }

  /**
   * Creates a multiplication assignment (`a *= b`).
   *
   * @example
   * ```ts
   * const mulAssignId = builder.SetNode(
   *   builder.CreateMulAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x *= y
   * ```
   */
  public CreateMulAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.MulAssign, a, b);
  }

  /**
   * Creates a division assignment (`a /= b`).
   *
   * @example
   * ```ts
   * const divAssignId = builder.SetNode(
   *   builder.CreateDivAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x /= y
   * ```
   */
  public CreateDivAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.DivAssign, a, b);
  }

  /**
   * Creates a modulo assignment (`a %= b`).
   *
   * @example
   * ```ts
   * const modAssignId = builder.SetNode(
   *   builder.CreateModAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x %= y
   * ```
   */
  public CreateModAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.ModAssign, a, b);
  }

  /**
   * Creates a bitwise AND assignment (`a &= b`).
   *
   * @example
   * ```ts
   * const andAssignId = builder.SetNode(
   *   builder.CreateBitAndAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x &= y
   * ```
   */
  public CreateBitAndAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitAndAssign, a, b);
  }

  /**
   * Creates a bitwise OR assignment (`a |= b`).
   *
   * @example
   * ```ts
   * const orAssignId = builder.SetNode(
   *   builder.CreateBitOrAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x |= y
   * ```
   */
  public CreateBitOrAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitOrAssign, a, b);
  }

  /**
   * Creates a bitwise XOR assignment (`a ^= b`).
   *
   * @example
   * ```ts
   * const xorAssignId = builder.SetNode(
   *   builder.CreateBitXorAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x ^= y
   * ```
   */
  public CreateBitXorAssignNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitXorAssign, a, b);
  }

  /**
   * Creates a bit clear assignment (`a &^= b`).
   *
   * @example
   * ```ts
   * const clearAssignId = builder.SetNode(
   *   builder.CreateBitClearAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x &^= y
   * ```
   */
  public CreateBitClearAssignNode(
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return this.createBinary(go.Opcode.BitClearAssign, a, b);
  }

  /**
   * Creates a left shift assignment (`a <<= b`).
   *
   * @example
   * ```ts
   * const shiftAssignId = builder.SetNode(
   *   builder.CreateLeftShiftAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x <<= y
   * ```
   */
  public CreateLeftShiftAssignNode(
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return this.createBinary(go.Opcode.LeftShiftAssign, a, b);
  }

  /**
   * Creates a right shift assignment (`a >>= b`).
   *
   * @example
   * ```ts
   * const shiftAssignId = builder.SetNode(
   *   builder.CreateRightShiftAssignNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x >>= y
   * ```
   */
  public CreateRightShiftAssignNode(
    a: string | NodeId,
    b: string | NodeId,
  ): Node {
    return this.createBinary(go.Opcode.RightShiftAssign, a, b);
  }

  /**
   * Creates an equality comparison (`a == b`).
   *
   * @example
   * ```ts
   * const eqId = builder.SetNode(
   *   builder.CreateEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x == y
   * ```
   */
  public CreateEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Equal, a, b);
  }

  /**
   * Creates an inequality comparison (`a != b`).
   *
   * @example
   * ```ts
   * const neId = builder.SetNode(
   *   builder.CreateNotEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x != y
   * ```
   */
  public CreateNotEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.NotEqual, a, b);
  }

  /**
   * Creates a less-than comparison (`a < b`).
   *
   * @example
   * ```ts
   * const ltId = builder.SetNode(
   *   builder.CreateLessNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x < y
   * ```
   */
  public CreateLessNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Less, a, b);
  }

  /**
   * Creates a less-than-or-equal comparison (`a <= b`).
   *
   * @example
   * ```ts
   * const leId = builder.SetNode(
   *   builder.CreateLessEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x <= y
   * ```
   */
  public CreateLessEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.LessEqual, a, b);
  }

  /**
   * Creates a greater-than comparison (`a > b`).
   *
   * @example
   * ```ts
   * const gtId = builder.SetNode(
   *   builder.CreateGreaterNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x > y
   * ```
   */
  public CreateGreaterNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Greater, a, b);
  }

  /**
   * Creates a greater-than-or-equal comparison (`a >= b`).
   *
   * @example
   * ```ts
   * const geId = builder.SetNode(
   *   builder.CreateGreaterEqualNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x >= y
   * ```
   */
  public CreateGreaterEqualNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.GreaterEqual, a, b);
  }

  /**
   * Creates a logical AND (`a && b`).
   *
   * @example
   * ```ts
   * const andId = builder.SetNode(
   *   builder.CreateAndNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x && y
   * ```
   */
  public CreateAndNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.And, a, b);
  }

  /**
   * Creates a logical OR (`a || b`).
   *
   * @example
   * ```ts
   * const orId = builder.SetNode(
   *   builder.CreateOrNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x || y
   * ```
   */
  public CreateOrNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.Or, a, b);
  }

  /**
   * Creates a logical NOT (`!a`).
   *
   * @example
   * ```ts
   * const notId = builder.SetNode(
   *   builder.CreateNotNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * !x
   * ```
   */
  public CreateNotNode(a: string | NodeId): Node {
    return this.createUnary(go.Opcode.Not, a);
  }

  /**
   * Creates a bitwise AND (`a & b`).
   *
   * @example
   * ```ts
   * const bitAndId = builder.SetNode(
   *   builder.CreateBitAndNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x & y
   * ```
   */
  public CreateBitAndNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitAnd, a, b);
  }

  /**
   * Creates a bitwise OR (`a | b`).
   *
   * @example
   * ```ts
   * const bitOrId = builder.SetNode(
   *   builder.CreateBitOrNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x | y
   * ```
   */
  public CreateBitOrNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitOr, a, b);
  }

  /**
   * Creates a bitwise XOR (`a ^ b`).
   *
   * @example
   * ```ts
   * const xorId = builder.SetNode(
   *   builder.CreateBitXorNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x ^ y
   * ```
   */
  public CreateBitXorNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitXor, a, b);
  }

  /**
   * Creates a bit clear (`a &^ b`).
   *
   * @example
   * ```ts
   * const clearId = builder.SetNode(
   *   builder.CreateBitClearNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x &^ y
   * ```
   */
  public CreateBitClearNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.BitClear, a, b);
  }

  /**
   * Creates a left shift (`a << b`).
   *
   * @example
   * ```ts
   * const shiftId = builder.SetNode(
   *   builder.CreateLeftShiftNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x << y
   * ```
   */
  public CreateLeftShiftNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.LeftShift, a, b);
  }

  /**
   * Creates a right shift (`a >> b`).
   *
   * @example
   * ```ts
   * const shiftId = builder.SetNode(
   *   builder.CreateRightShiftNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * x >> y
   * ```
   */
  public CreateRightShiftNode(a: string | NodeId, b: string | NodeId): Node {
    return this.createBinary(go.Opcode.RightShift, a, b);
  }

  /** ch <- value */
  public CreateChanSendNode(chan: NodeId, value: NodeId): Node {
    return this.createBinary(go.Opcode.Send, chan, value);
  }

  /** <-ch */
  public CreateChanReceiveNode(chan: NodeId): Node {
    return this.createUnary(go.Opcode.Receive, chan);
  }

  /**
   * Creates an address-of expression (`&a`).
   *
   * @example
   * ```ts
   * const addrId = builder.SetNode(
   *   builder.CreateAddrOfNode(xId, yId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * &x
   * ```
   */
  public CreateAddrOfNode(value: NodeId): Node {
    return this.createUnary(go.Opcode.AddrOf, value);
  }

  /**
   * Dereferences a pointer (`*ptr`).
   *
   * @example
   * ```ts
   * const ptrId = builder.SetNode(
   *   builder.CreateDerefNode(ptr)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * *ptr
   * ```
   */
  public CreateDerefNode(ptr: NodeId): Node {
    return this.createUnary(go.Opcode.Deref, ptr);
  }

  /**
   * Represents a function or method call.
   *
   * @param funcId Function name or selector
   * @param params Arguments (literals or {@link NodeId}s)
   *
   * @example
   * ```ts
   * const callId = builder.SetNode(
   *   builder.CreateCallNode("fmt.Println", ["Hello, world!"])
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * fmt.Println("Hello, world!")
   * ```
   */
  public CreateCallNode(funcId: string, params: (NodeId | string)[]): Node {
    return this.createIndexed(
      go.Opcode.Call,
      funcId,
      params.map((v) => this.makeValue(v)),
    );
  }

  /**
   * Creates a `return` statement.
   *
   * Each NodeId in `params` represents an expression to be returned.
   * An empty array represents a bare `return`.
   *
   * @example
   * ```ts
   * const aId = builder.SetNode(
   *   builder.CreateVarValueNode("a", intType, "0")
   * );
   * const bId = builder.SetNode(
   *   builder.CreateVarValueNode("b", intType, "0")
   * );
   *
   * const returnId = builder.SetNode(
   *   builder.CreateReturnNode([ aId, bId ])
   * );
   *
   * builder.ConnectNodes(funcId, returnId);
   *```
   *
   * Compiler output:
   * ```go
   * return a, b
   * ```
   */
  public CreateReturnNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Return,
      undefined,
      this.makePtrFields(params),
    );
  }

  /**
   * Creates a `defer` statement.
   *
   * The operand MUST be a call node.
   *
   * @example
   * ```ts
   * const callId = builder.SetNode(
   *   builder.CreateCallNode("fmt.Println", ["Hello, world!"])
   * );
   *
   * const deferId = builder.SetNode(
   *   builder.CreateDeferNode(callId)
   * );
   *
   * builder.ConnectNodes(funcId, deferId);
   * ```
   *
   * Compiler output:
   * ```go
   * defer fmt.Println("Hello, world!")
   * ```
   */
  public CreateDeferNode(call: NodeId): Node {
    return this.createUnary(go.Opcode.Defer, call);
  }

  /**
   * Creates a goroutine invocation
   *
   * @example
   * ```ts
   * const callId = builder.SetNode(
   *   builder.CreateCallNode("worker", [])
   * );
   *
   * const goId = builder.SetNode(
   *   builder.CreateGoRoutineNode(callId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * go worker()
   * ```
   * */
  public CreateGoRoutineNode(call: NodeId): Node {
    return this.createUnary(go.Opcode.GoRoutine, call);
  }

  // public CreateMapNode(mapDef: TypeDef, body: NodeId[]): Node {
  //   // WARN - needs attention
  //   // return this.createIndexed(go.Opcode.Map, undefined, this.makePtrFields(body));
  // }

  // public CreateArrayNode(arrayDef: TypeDef, body: NodeId[]): Node {
  //   // WARN - needs attention
  //   // return this.createIndexed(go.Opcode.Array, undefined, this.makePtrFields(body));
  // }

  /**
   * Creates a panic call.
   *
   * @example
   * ```ts
   * const panicId = builder.SetNode(
   *   builder.Panic(xId)
   * );
   * ```
   *
   * ```go
   * panic(x)
   * ```
   */
  public Panic(expression: NodeId): Node {
    return this.createUnary(go.Opcode.Panic, expression);
  }

  /**
   * Creates a `recover()` builtin call
   */
  public Recover(): Node {
    return {
      opcode: go.Opcode.Recover,
      flags: go.NodeFlag.None,
    };
  }

  /**
   * Creates a `make` builtin call.
   *
   * @example
   * ```ts
   * const makeId = builder.SetNode(
   *   builder.CreateMakeNode([sliceTypeId])
   * );
   * ```
   *
   * ```go
   * make([]int)
   * ```
   */
  public CreateMakeNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Make,
      undefined,
      this.makePtrFields(params),
    );
  }

  /**
   * Allocates a new value.
   *
   * @example
   * ```ts
   * const newId = builder.SetNode(
   *   builder.New(myType)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * new(T)
   * ```
   */
  public New(_type: GoType): Node {
    return this.createUnary(go.Opcode.New, 0n);
  }

  /**
   * Gets the length of a value (`len(x)`).
   *
   * For slices, this is the number of elements currently in use.
   *
   * @example
   * ```ts
   * const lenId = builder.SetNode(
   *   builder.CreateLenNode(sliceId)
   * );
   * ```
   *
   * ```go
   * len(slice)
   * ```
   */
  public CreateLenNode(param: NodeId): Node {
    return this.createUnary(go.Opcode.Len, param);
  }

  /**
   * Returns the capacity of a value `cap(x)`.
   *
   * For slices, this is the maximum size before reallocation.
   *
   * @example
   * ```ts
   * const capId = builder.SetNode(
   *   builder.CreateCapNode(sliceId)
   * );
   * ```
   *
   * ```go
   * cap(slice)
   * ```
   */
  public CreateCapNode(param: NodeId): Node {
    return this.createUnary(go.Opcode.Cap, param);
  }

  /**
   * Appends values to a slice.
   *
   * @example
   * ```ts
   * const appendId = builder.SetNode(
   *   builder.CreateAppendNode([sliceId, valueId])
   * );
   * ```
   *
   * ```go
   * append(slice, value)
   * ```
   */
  public CreateAppendNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Append,
      undefined,
      this.makePtrFields(params),
    );
  }

  /**
   * Copies elements between slices.
   *
   * @example
   * ```ts
   * const copyId = builder.SetNode(
   *   builder.CreateCopyNode(dstId, srcId)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * copy(dst, src)
   * ```
   */
  public CreateCopyNode(dst: NodeId, src: NodeId): Node {
    return this.createBinary(go.Opcode.Copy, dst, src);
  }

  /**
   * Closes a channel.
   *
   * @example
   * ```ts
   * const closeId = builder.SetNode(
   *   builder.CreateCloseNode(chanType)
   * );
   * ```
   *
   * Compiler output:
   * ```go
   * close(ch)
   * ```
   */
  public CreateCloseNode(chan: GoType): Node {
    // WARN - NEEDS ATTENTION
    return this.createUnary(go.Opcode.Close, 0n);
  }

  public CreateComplexNode(r: string, i: string): Node {
    return this.createBinary(go.Opcode.Complex, r, i);
  }

  public CreateRealNode(c: NodeId): Node {
    return this.createUnary(go.Opcode.Real, c);
  }

  public CreateImagNode(c: NodeId): Node {
    return this.createUnary(go.Opcode.Imag, c);
  }

  public CreatePrintNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Print,
      undefined,
      this.makePtrFields(params),
    );
  }

  public CreatePrintlnNode(params: NodeId[]): Node {
    return this.createIndexed(
      go.Opcode.Println,
      undefined,
      this.makePtrFields(params),
    );
  }


  private SerializeType(t: GoTypeDef): fb.Offset {
    let typeOffset: fb.Offset = 0;
    //let typeEnum = program.Type.NONE;
    let base: go.Kind = go.Kind.nil;
    let basePtr: boolean = false;
    let flags: number = 0;
    switch (t.base) {
      case GoKind.FUNC:
        typeOffset = this.CreateFuncType(t as GoFunctionType);
        //typeEnum = program.Type.FunctionType;
        break;
      case GoKind.SLICE:
      case GoKind.ARRAY:
        typeOffset = this.CreateArrayType(t as GoArrayType);
        //typeEnum = program.Type.ArrayType;
        break;
      case GoKind.MAP:
        typeOffset = this.CreateMapType(t as GoMapType);
        //typeEnum = program.Type.MapType;
        break;
      case GoKind.INTERFACE:
        typeOffset = this.CreateInterfaceType(t as GoInterfaceType);
        //typeEnum = program.Type.StructureType;
        break;
      case GoKind.STRUCT:
        typeOffset = this.CreateStructType(t as GoStructType);
        //typeEnum = program.Type.StructureType;
        break;
      case GoKind.POINTER:
        typeOffset = this.CreatePointerType(t as GoPointerType);
        //typeEnum = program.Type.PointerType;
        break;
      case GoKind.BOOLEAN:
      case GoKind.CHANNEL:
      case GoKind.BYTE:
      case GoKind.COMPLEX128:
      case GoKind.COMPLEX64:
      case GoKind.FLOAT32:
      case GoKind.FLOAT64:
      case GoKind.INT:
      case GoKind.INT16:
      case GoKind.INT32:
      case GoKind.INT64:
      case GoKind.INT8:
      case GoKind.RUNE:
      case GoKind.STRING:
      //case GoKind.UINT:
      case GoKind.UINT16:
      case GoKind.UINT32:
      case GoKind.UINT64:
      case GoKind.UINT8:
      case GoKind.UINTPTR:
        break;
      default:
        basePtr = true;
        const baseResult = this.typelut.findIndex((v) => v.id == t.base);
        if (baseResult == -1)
          throw Error(
            `type ${t.id} requires a valid base type. Type must be set before inheritance.`,
          );
        base = baseResult;
    }

    if (!basePtr) {
      base = KindMapper(t.base as GoKind);
    }

    go.TypeDef.startTypeDef(this.builder);
    go.TypeDef.addBase(this.builder, base);
    go.TypeDef.addId(this.builder, this.SetString(t.id));
    //go.TypeDef.addTypeType(this.builder, typeEnum);
    go.TypeDef.addType(this.builder, typeOffset);
    go.TypeDef.addFlags(this.builder, flags);

    return go.TypeDef.endTypeDef(this.builder);
  }

  public SetType(t: GoTypeDef): number {
    // check if type already exists
    let uid = this.typelut.findIndex((v) => v && v.id === t.id);
    if (uid >= 0) return uid;

    uid = this.nextTypeId++ >>> 0;
    if (uid > 0xfffffffe) {
      throw new Error("uint32 overflow");
    }

    this.typelut[uid] = {
      id: t.id,
      type: t,
    };

    return uid;
  }

  private CreateFuncType(func: GoFunctionType): fb.Offset {
    let paramsList: bigint[] = [];
    for (const [val, ty] of func.params) {
      const value = this.SetString(val);
      const type = this.SetType(ty);

      paramsList.push(
        (BigInt(value) << 32n) | BigInt(type)
      );
    }

    const params = go.Type.createParamsVector(this.builder, paramsList);

    let resultsList: bigint[] = [];
    for (const [val, ty] of func.results) {
      const value = this.SetString(val);
      const type = this.SetType(ty);

      resultsList.push(
        (BigInt(value) << 32n) | BigInt(type)
      );
    }

    const results = go.Type.createResultsVector(this.builder, resultsList);

    go.Type.startType(this.builder);
    go.Type.addParams(this.builder, params);
    go.Type.addResults(this.builder, results);

    return go.Type.endType(this.builder);
  }

  private CreateArrayType(arr: GoArrayType): fb.Offset {
    const size = packIntArrayToBigInt(arr.size, 64 / arr.size.length);

    const elem = this.SetType(arr.elem);

    go.Type.startType(this.builder);
    go.Type.addSize(this.builder, size);
    go.Type.addElem(this.builder, elem);

    return go.Type.endType(this.builder);
  }

  private CreateMapType(map: GoMapType): fb.Offset {
    const key = this.SetType(map.key);
    const value = this.SetType(map.value);

    go.Type.startType(this.builder);
    go.Type.addKey(this.builder, key);
    go.Type.addValue(this.builder, value);

    return go.Type.endType(this.builder);
  }

  private CreateStructType(struct: GoStructType): fb.Offset {
    go.Type.startType(this.builder);
    go.Type.startFieldsVector(this.builder, struct.fields.length);

    for (let i = struct.fields.length - 1; i >= 0; i--) {
      const field = struct.fields[i];

      const name = this.SetString(field.name);
      const type = this.SetType(field.type);
      const misc = field.tag ? this.SetString(field.tag) : 0;

      go.StructField.createStructField(
        this.builder, name, type, misc
      );
    }

    const fieldsVector = this.builder.endVector();
    go.Type.addFields(this.builder, fieldsVector);

    return go.Type.endType(this.builder);
  }

  private CreateInterfaceType(_interface: GoInterfaceType): fb.Offset {
    const methods: bigint[] = [];

    for (const method of _interface.methods) {
      const id = this.SetString(method.id);
      const type = this.SetType(method);

      methods.push(
        (BigInt(id) << 32n) | BigInt(type)
      );
    }

    const methodsOffset = go.Type.createMethodsVector(this.builder, methods);

    go.Type.startType(this.builder);
    go.Type.addMethods(this.builder, methodsOffset);

    return go.Type.endType(this.builder);
  }

  private CreatePointerType(ptr: GoPointerType): fb.Offset {
    const _type = this.SetType(ptr.elem);
    go.Type.startType(this.builder);
    go.Type.addElem(this.builder, _type);

    return go.Type.endType(this.builder);
  }


  private resolveNodeValue(v: GoNodeValue) {
    return {
      value: typeof v.value === "string"
        ? BigInt(this.SetString(v.value))
        : v.value ?? 0n,

      type: v.type !== undefined
        ? this.SetType(v.type)
        : 0,

      flags: v.flags
    };
  }

  private buildNodeValue(v: {
    value: bigint,
    type: number,
    flags: number
  }): fb.Offset {
    return program.NodeValue.createNodeValue(
      this.builder, v.value, v.type, v.flags
    );
  }

  private CreateIndexedNode(node: Node): fb.Offset {
    const values = node.fields?.map((v) => this.resolveNodeValue(v)) ?? [];

    program.IndexedNode.startFieldsVector(this.builder, values.length);
    for (let i = values.length - 1; i >= 0; i--) {
      this.buildNodeValue(values[i]);
    }

    const fieldsVector = this.builder.endVector();

    program.IndexedNode.startIndexedNode(this.builder);
    program.IndexedNode.addId(this.builder, node.id ?? 0);
    program.IndexedNode.addFields(this.builder, fieldsVector);

    return program.IndexedNode.endIndexedNode(this.builder);
  }

  private CreateBinaryNode(node: Node): fb.Offset {
    const left = node.left ? this.resolveNodeValue(node.left) : undefined;
    const right = node.right ? this.resolveNodeValue(node.right) : undefined;

    program.BinaryNode.startBinaryNode(this.builder);

    if (left) {
      this.buildNodeValue(left);

      program.BinaryNode.addLeft(
        this.builder,
        this.builder.offset()
      );
    }

    if (right) {
      this.buildNodeValue(right);

      program.BinaryNode.addRight(
        this.builder,
        this.builder.offset()
      );
    }
    
    return program.BinaryNode.endBinaryNode(this.builder);
  }

  private CreateUnaryNode(node: Node): fb.Offset {
    const value = node.value ? this.resolveNodeValue(node.value) : undefined;

    program.UnaryNode.startUnaryNode(this.builder);

    if (value) {
      this.buildNodeValue(value);
      
      program.UnaryNode.addValue(
        this.builder,
        this.builder.offset()
      );
    }

    return program.UnaryNode.endUnaryNode(this.builder);
  }

  // Export
  public CreateStringLUT(): fb.Offset {
    const offsets: fb.Offset[] = [];

    for (const [id, str] of this.stringlut) {
      const valueOffset = this.builder.createString(str);

      program.StringEntry.startStringEntry(this.builder);
      program.StringEntry.addKey(this.builder, id);
      program.StringEntry.addValue(this.builder, valueOffset);

      offsets.push(
        program.StringEntry.endStringEntry(this.builder)
      );
    }

    return go.App.createLutVector(this.builder, offsets);
  }

  public CreateTypeLUT(): fb.Offset {
    const offsets: fb.Offset[] = [];
  
    for (let i = 0; i < this.typelut.length; i++) {
      const entry = this.typelut[i];
      if (!entry) {
        continue;
      }
      const addr = this.SerializeType(entry.type);

      go.TypeEntry.startTypeEntry(this.builder);
      go.TypeEntry.addKey(this.builder, i);
      go.TypeEntry.addValue(this.builder, addr);
  
      offsets.push(
        go.TypeEntry.endTypeEntry(this.builder)
      );
    }
  
    return go.App.createTypesVector(this.builder, offsets);
  }

  public buildApp(flags: number): Uint8Array {
    const typeLut: fb.Offset = this.CreateTypeLUT();
    const stringLut: fb.Offset = this.CreateStringLUT();
  
    const name = this.builder.createString(
      this.builderOptions.name ?? "Unnamed Program",
    );
  
    go.App.startApp(this.builder);
    //go.App.addNodes(this.builder, nodesVector);
  
    go.App.addLut(this.builder, stringLut);
    go.App.addTypes(this.builder, typeLut);
    go.App.addFlags(this.builder, flags);
    go.App.addName(this.builder, name);
  
    const programOffset = go.App.endApp(this.builder);
    
    this.builder.finish(programOffset);
    return this.builder.asUint8Array();
  }
}