// NOTE: These below functions were generated by gemini-2.5-flash due to the fact that it is annoying to create in typescript

/**
 * Packs an array of non-negative integers into a single BigInt.
 * Each integer in the array will occupy a fixed number of bits as specified by `bitsPerElement`.
 *
 * @param intArray The array of non-negative integers to pack.
 * @param bitsPerElement The number of bits each integer in the array will occupy.
 *                       Must be a positive integer.
 *                       For example:
 *                       - 8 bits allows numbers from 0 to 255.
 *                       - 16 bits allows numbers from 0 to 65535.
 *                       - 32 bits allows numbers from 0 to 4,294,967,295.
 * @returns A BigInt representing the packed array.
 * @throws Error if `bitsPerElement` is invalid or an integer in `intArray` exceeds its allowed bit-width.
 */
export function packIntArrayToBigInt(
  intArray: number[],
  bitsPerElement: number,
): bigint {
  if (!Number.isInteger(bitsPerElement) || bitsPerElement <= 0) {
    throw new Error("bitsPerElement must be a positive integer.");
  }

  // Calculate the maximum value an element can hold given `bitsPerElement`
  // (1n << BigInt(bitsPerElement)) is 2^bitsPerElement
  const maxValPerElement = (1n << BigInt(bitsPerElement)) - 1n;

  let packedBigInt: bigint = 0n;

  for (const num of intArray) {
    if (!Number.isInteger(num) || num < 0) {
      throw new Error(
        `Array must contain only non-negative integers. Found: ${num}`,
      );
    }
    const bigNum = BigInt(num);

    if (bigNum > maxValPerElement) {
      throw new Error(
        `Integer ${num} exceeds the maximum value allowed by ${bitsPerElement} bits (${maxValPerElement}).`,
      );
    }

    // Shift the existing packed BigInt to make space for the new number
    packedBigInt <<= BigInt(bitsPerElement);
    // OR the new number into the least significant bits
    packedBigInt |= bigNum;
  }

  return packedBigInt;
}

/**
 * Unpacks a BigInt back into an array of non-negative integers.
 *
 * @param packedBigInt The BigInt to unpack.
 * @param originalArrayLength The original number of elements in the array before packing.
 *                            This is crucial to know how many elements to extract.
 * @param bitsPerElement The number of bits each integer originally occupied.
 *                       Must match the value used during packing.
 * @returns The unpacked array of numbers.
 * @throws Error if `bitsPerElement` is invalid or if a value extracted exceeds
 *         the safe integer limit for JavaScript numbers (2^53 - 1).
 */
export function unpackBigIntToIntArray(
  packedBigInt: bigint,
  originalArrayLength: number,
  bitsPerElement: number,
): number[] {
  if (!Number.isInteger(bitsPerElement) || bitsPerElement <= 0) {
    throw new Error("bitsPerElement must be a positive integer.");
  }
  if (!Number.isInteger(originalArrayLength) || originalArrayLength < 0) {
    throw new Error("originalArrayLength must be a non-negative integer.");
  }

  // Mask to isolate the `bitsPerElement` least significant bits
  const elementMask = (1n << BigInt(bitsPerElement)) - 1n;

  // JavaScript's Number type can safely represent integers up to 2^53 - 1.
  // If bitsPerElement is too large, converting to Number might lose precision.
  const MAX_SAFE_BITS_FOR_NUMBER = 53;
  if (bitsPerElement > MAX_SAFE_BITS_FOR_NUMBER) {
    console.warn(
      `Warning: bitsPerElement (${bitsPerElement}) is greater than MAX_SAFE_BITS_FOR_NUMBER ` +
        `(${MAX_SAFE_BITS_FOR_NUMBER}). Unpacked numbers might lose precision if they exceed 2^53 - 1.`,
    );
    // For strict type safety, you might consider returning bigint[] here,
    // or throw an error if the user demands number[] output.
    // For this example, we proceed with Number() conversion.
  }

  const unpackedArray: number[] = [];
  let tempBigInt = packedBigInt;

  // We unpack from the least significant bits, so we need to add to the front
  // or reverse the array at the end. Adding to the front (unshift) maintains order.
  for (let i = 0; i < originalArrayLength; i++) {
    // Extract the least significant `bitsPerElement`
    const elementBigInt = tempBigInt & elementMask;
    unpackedArray.unshift(Number(elementBigInt)); // Convert BigInt to Number

    // Shift right to prepare for the next element
    tempBigInt >>= BigInt(bitsPerElement);
  }
  return unpackedArray;
}
