// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { GoType } from './golang/go-type.js';
export { Kind } from './golang/kind.js';
export { NodeFlag } from './golang/node-flag.js';
export { Opcode } from './golang/opcode.js';
export { StructField } from './golang/struct-field.js';
export { ValueFlag } from './golang/value-flag.js';
