// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ID {
  Verification = 0,
  RVerification = 1,
  SetNode = 2,
  DeleteNode = 3,
  ConnectNodes = 4,
  UpdateNodeField = 5,
  Export = 6
}
